import { Project } from '@/components/cards/ProjectCard';

export const PROJECTS: Project[] = [
  {
    title: 'Aura Stream',
    description: 'Full-stack streaming platform leveraging TMDB API for movies and shows with PostgreSQL, Prisma, and Next.js backend.',
    tech: ['TypeScript', 'Next.js', 'PostgreSQL', 'Prisma', 'Zustand', 'TMDB API'],
    href: 'https://aura-stream.vercel.app/',
    githubMonorepo: 'https://github.com/odedsam/stream-vibe',
    imageUrl: '/thumb/aura-stream-browse.png',
    pinned: true,
  },
  {
    title: 'Estatein RealEstate',
    description: 'High-end real estate website with property listings, filters, and booking system.',
    tech: ['TypeScript', 'Nuxt 3', 'Vue 3', 'Pinia', 'Tailwind', 'FirebaseDB'],
    href: 'https://estate-app-nuxt3.vercel.app',
    githubMonorepo: 'https://github.com/odedsam/Estate-App-nuxt3',
    imageUrl: '/thumb/esa-thumb.png',
    pinned: true,
  },
  {
    title: 'Noad',
    description: 'Real-time cryptocurrency dashboard with live price updates, interactive charts, and global market stats.',
    tech: ['React', 'Zustand', 'Recharts', 'WebSockets'],
    href: 'https://noad.vercel.app',
    imageUrl: '/thumb/noad-thumbnail.png',
    githubMonorepo: 'https://github.com/odedsam/crypto-dash',
  },
  {
    title: 'Explore Moon',
    description: 'Real-time cryptocurrency dashboard with live price updates, interactive charts, and global market stats.',
    tech: ['React', 'Zustand', 'Recharts', 'WebSockets'],
    href: 'https://explore-moon.vercel.app',
    imageUrl: '/thumb/explore-moon-thumbnail.png',
    githubMonorepo: 'https://github.com/odedsam/explore-moon',
  },

  {
    title: 'Pierced',
    description: 'Real-time cryptocurrency dashboard with live price updates, interactive charts, and global market stats.',
    tech: ['React', 'Zustand', 'Recharts', 'WebSockets'],
    href: 'https://pierced.vercel.app/',
    imageUrl: '/thumb/pierced-thumbnail.png',
    githubMonorepo: 'https://github.com/odedsam/Pierced',
  },
  {
    title: 'Candleaf E‑Commerce',
    description: 'Minimalist online store built with Next.js, TailwindCSS, and Stripe integration.',
    tech: ['TypeScript', 'Vue 3', 'NodeJs', 'MongoDB', 'GoogleAuth', 'Tailwind', 'Stripe', 'Express'],
    href: 'https://candleaf-front.vercel.app',
    githubClientUrl: 'https://github.com/odedsam/candleaf-front',
    githubServerUrl: 'https://github.com/odedsam/candleaf-back',
    imageUrl: '/thumb/candleaf-thumbnail.png',
    pinned: true,
  },

  {
    title: 'Avion E‑Commerce',
    description: 'Scalable e‑commerce app with CMS integration, shopping cart, and responsive UI.',
    tech: ['TypeScript', 'React', 'Tailwind', 'NestJS', 'ReduxRTK', 'MongoDB'],
    href: 'https://avion-steel.vercel.app/',
    githubClientUrl: 'https://github.com/odedsam/avion-new-react-18',
    githubServerUrl: 'https://github.com/odedsam/avm-back',
    imageUrl: '/thumb/avion-thumbnail.png',
    pinned: true,
  },

  {
    title: 'Hasa Media',
    description: 'Media services agency website with CMS-managed content and service showcase.',
    tech: ['TypeScript', 'React', 'CMS', 'PHP'],
    href: 'https://hasamedia.io',
    githubClientUrl: 'https://github.com/odedsam/Hasamedia',
    githubMonorepo: 'https://github.com/odedsam/Hasamedia',
    imageUrl: '/thumb/hasamedia-thumbnail.png',
    pinned: true,
  },

  {
    title: 'Lernaean',
    description: 'Real-time cryptocurrency dashboard with live price updates, interactive charts, and global market stats.',
    tech: ['React', 'Zustand', 'Recharts', 'WebSockets'],
    href: 'https://lernaean.vercel.app/',
    imageUrl: '/thumb/lernaean-thumbnail.png',
    githubMonorepo: 'https://github.com/odedsam/lernaean',
  },
  {
    title: 'Cyber Skin',
    description: 'Real-time cryptocurrency dashboard with live price updates, interactive charts, and global market stats.',
    tech: ['React', 'Zustand', 'Recharts', 'WebSockets'],
    href: 'https://cyberskin.vercel.app/',
    imageUrl: '/thumb/cyberskin-thumbnail.png',
    githubMonorepo: 'https://github.com/odedsam/cyberskin',
  },
  {
    title: 'Crypto Pulse',
    description: 'Real-time cryptocurrency dashboard with live price updates, interactive charts, and global market stats.',
    tech: ['React', 'Zustand', 'Recharts', 'WebSockets'],
    href: 'https://crypto-dash-flame.vercel.app',
    imageUrl: '/thumb/cryptodash-thumbnail.png',
    githubMonorepo: 'https://github.com/odedsam/crypto-dash',
  },
];
